### ISSUE TITLE
Potion settings

### ISSUE THREAD

**Issue by AlexanderRitter02** [AlexanderRitter02/Varo-Plugin#21]
**Is this related to a problem?**
Potions are hardcoded and would be hard to block even after implementation of #20, because there are too many potion variations with different ids.
This is especially problematic e.g. if one tried to block all splash potions.

**The suggestion**
A seperate option in `config.yml`, that allows to:
1. Deactivate potions completely
2. Deactivate splash potions
3. Disallow specific potions in human readable format (`strength` instead of `8201`).
In doing so, the amplified and long-duration variant of the potion should be disallowed too.

**Default**
```
potions:
  enabled: true
  splash-potions: false
  disabled-potions:
     - strength
     - invisibility
     - regeneration
  
```
